!keyword
type=optxg
nsteps=100
qm-type=gauss
qmem=500MB
geomem=500MB
?keyword

!sander 
comment line 
&cntrl 
imin   = 1, 
maxcyc = 0, 
ntb    = 0, 
igb    = 0,
ntr    = 0, 
ibelly = 1, 
cut    = 10 
/
?sander

!gaussian 
#p STO-3G HF nosym 

gaussian input generated by COBRAMM 

0 1 
?gaussian

